#!/usr/bin/env bash
#
# This script fetches jenkins build info from the apsimdev web services.
set -e
test -z ${PULL_ID:+x} && ( echo "PULL_ID not set"; exit 1 )

temp_file=$(mktemp)
curl -ks https://apsimdev.apsim.info/APSIM.Builds.Service/Builds.svc/GetPullRequestDetails?pullRequestID=$PULL_ID >$temp_file
response=$(sed -e 's/<[^>]*>//g' $temp_file)
rm $temp_file
arr=(${response//,/ })
export TIMESTAMP=${arr[0]}
export DATE=(${TIMESTAMP//-/ })
export ISSUE_ID=${arr[1]}
export VERSION=$DATE.$ISSUE_ID
