#!/usr/bin/env bash
set -e

# Clone and build apsim
./main
cd ApsimX

# Extract password-protected datasets.
grapevine=Prototypes/Grapevine unzip -oP $GRAPEVINE_PASSWORD -d $grapevine $grapevine/Observations.zip
soybean=Tests/UnderReview/Soybean 7z -p$SOYBEAN_PASSWORD x $soybean/ObservedFACTS.7z -o$soybean
wheat=Tests/Validation/Wheat 7z -p$NPI_PASSWORD x $wheat/NPIValidation.7z -o$wheat

# Run all .apsimx files outside of ./Tests and ./ApsimNG
find . -not \\( -path ./Tests/UnitTests -prune \\) -not \\( -path ./ApsimNG -prune \\)  -name '*.apsimx' -print0 | xargs -0 dotnet NetCoreBin/Models.dll --verbose --run-tests
