#!/usr/bin/env bash
set -e

# Clone and build apsim
./main
cd ApsimX

# Extract password-protected datasets.
unzip -oP $GRAPEVINE_PASSWORD -d Prototypes/Grapevine Prototypes/Grapevine/Observations.zip
7z -p$SOYBEAN_PASSWORD x Tests/UnderReview/Soybean/ObservedFACTS.7z -oTests/UnderReview/Soybean
7z -p$NPI_PASSWORD x Tests/Validation/Wheat/NPIValidation.7z -oTests/Validation/Wheat

# Run all .apsimx files outside of ./Tests and ./ApsimNG
find . -not \\( -path ./Tests/UnitTests -prune \\) -not \\( -path ./ApsimNG -prune \\)  -name '*.apsimx' -print0 | xargs -0 dotnet NetCoreBin/Models.dll --verbose --run-tests
